In [22]:
import tensorflow as tf


In [23]:
x = tf.constant([[0, -1, -2], [0, 1, 2]])
y = tf.zeros(x.shape, tf.int32)
r = tf.equal(x, y)

In [24]:
with tf.Session() as sess:
    print (sess.run(r))


[[ True False False]
 [ True False False]]


In [25]:
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858])
idx = tf.where(x > 30)
y = tf.gather(x, idx)

In [26]:
with tf.Session() as sess:
    print(sess.run(idx))
    print(sess.run(y))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [29]:
diag = tf.range(1,7)
out = tf.diag(diag)
with tf.Session() as sess:
    print (sess.run(out))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [47]:
x = tf.random_uniform((10,10), 0, 1)
output = tf.matrix_determinant(x)
with tf.Session() as sess:
    print (sess.run(output))

0.00859201


In [51]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
output, idx = tf.unique(x)
with tf.Session() as sess:
    print(sess.run(output))

[ 5  2  3 10  6  4  1  0  9]


In [ ]:
x = tf.random_uniform([300])
y = tf.random_uniform([300])
avg = tf.reduce_mean(x -y)
def f1(): return tf.square(avg)
def f2(): return tf.reduce_sum(tf.abs(x-y))
output = tf.cond(avg < 0, f1, f2)
with tf.Session() as sess:
    print(sess.run(output))

98.3889
